os: Visual Studio 2015

platform: x64

install:
    - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
    - appveyor-retry choco install strawberryperl --allow-empty-checksums
    - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    - appveyor DownloadFile "http://rakudo.org/downloads/star/rakudo-star-latest-x86_64 (JIT).msi" -FileName "%APPVEYOR_BUILD_FOLDER%\rakudo.msi"
    - msiexec /i rakudo.msi /quiet /qn /norestart /log install.log
    - SET PATH=C:\rakudo\bin;C:\rakudo\share\perl6\site\bin;%PATH%
    - SET ZEF_PLUGIN_DEBUG=1
    - SET ZEF_BUILDPM_DEBUG=1

build: off

test_script:
    # test local path install
    - perl6 -Ilib bin/zef --debug install .

    # change path to make sure next `zef` commands aren't using any files in cwd or lib/
    - cd %APPVEYOR_BUILD_FOLDER%\..

    # test bells and whistles
    - zef --debug test ./zef
    - zef --debug update
    - zef --debug search Base64
    - zef --debug info Base64
    - zef --debug rdepends Base64
    - zef --debug fetch Base64
    - zef --debug install Base64
    - zef --debug --max=10 list
    - zef --debug --installed list

    - zef --debug install http://hack.p6c.org:5001/authors/id/P/PS/PSIXDISTS/Perl6/CSV-Parser-0.000.002_1601022004.tar.gz
    - zef --debug upgrade CSV::Parser

    - zef --/confirm nuke TempDir StoreDir RootDir
    - zef update cached # test single repository update; should be 0 after previous nuke
    - zef --/confirm nuke site home # no more `zef` command

shallow_clone: true
