os: Visual Studio 2015

platform: x64

install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - choco install strawberryperl
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - git clone https://github.com/rakudo/rakudo.git %APPVEYOR_BUILD_FOLDER%\..\rakudo
  - cd %APPVEYOR_BUILD_FOLDER%\..\rakudo
  - perl Configure.pl --gen-moar=HEAD --gen-nqp
  - nmake install
  - SET PATH=%APPVEYOR_BUILD_FOLDER%\..\rakudo\install\bin;%PATH%
  - SET ZEF_PLUGIN_DEBUG=1
  - cd %APPVEYOR_BUILD_FOLDER%

build: off

test_script:
  # Sanity
  - prove -v -e "perl6 -Ilib" t/

  # Can install itself (or anything) without being installed itself
  - perl6 -Ilib bin/zef --verbose install .

  # Setup PATH to give access to the `zef` command (shown in stdout of prev command)
  - SET PATH=%APPVEYOR_BUILD_FOLDER%\..\rakudo\install\share\perl6\site\bin;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%\..

  # Test that our installed bin/ script works, as well as basic ::ContentStorage::P6C functionality
  # [--force]: Its reinstalling the same version (or an unversioned) copy; tells CU::R::I this is ok
  # [--/test]: Disable testing. Already tested twice (see: `prove` and `bin/zef install .`)
  - zef -v --force --/test install CSV::Parser

shallow_clone: true
