language: perl
perl:
    - '5.20-shrplib'
os:
    - linux
    - osx
env:
    - BACKEND=moar
    - BACKEND=jvm
matrix:
    allow_failures:
        - env: BACKEND=jvm
    fast_finish: true
sudo: false
before_install:
    - 'if [[ $BACKEND == "moar" ]]; then export VM_OPTS="--gen-moar"; fi'
    - git clone https://github.com/rakudo/rakudo.git $HOME/rakudo
    - cd $HOME/rakudo
    - perl Configure.pl $VM_OPTS --gen-nqp --backends=$BACKEND
    - make install
    - export PATH=$HOME/rakudo/install/bin:$PATH
    - export ZEF_PLUGIN_DEBUG=1
    - cd $TRAVIS_BUILD_DIR
install:
    # need at least 1 statement in 'install'
    - perl6 -v
script:
    - perl6 -Ilib bin/zef -v install .
after_success:
    - export PATH=$HOME/rakudo/install/share/perl6/site/bin:$PATH
    # perl/perlbrew setup for osx on travis is buggy; not sure how to use shrplib perl without building from source
    - 'if [[ $TRAVIS_OS_NAME == "linux" ]]; then zef -v install Inline::Perl5; fi'
    - 'if [[ $TRAVIS_OS_NAME == "linux" ]]; then perl6 -MInline::Perl5 -e "exit 0;"; fi'
