language: perl
perl:
    - '5.20'
env:
    - BACKEND=moar ASYNC=""
    - BACKEND=moar ASYNC="--async"
    - BACKEND=jvm  ASYNC=""
    - BACKEND="moar glr" ASYNC=""
    - BACKEND="moar glr" ASYNC="--async"
matrix:
    allow_failures:
        - env: BACKEND=jvm  ASYNC=""
        - env: BACKEND=moar ASYNC="--async"
        - env: BACKEND="moar glr" ASYNC="--async"
    fast_finish: true
sudo: false
before_install:
    - git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    - export PATH=~/.rakudobrew/bin:$PATH
    - rakudobrew build $BACKEND
install:
    # need at least 1 statement in 'install'
    - perl6 -v
script:
    - prove -j4 -v -e "perl6 -Ilib" t/ xt/
after_success:
    # test running with precompiled code

    - 'if [[ $BACKEND == "moar" ]]; then perl6 -Ilib bin/zef -v --boring $ASYNC --save-to=precomp/ build; fi'
    - 'if [[ $BACKEND == "moar" ]]; then perl6 -Iprecomp bin/zef -v --boring --lib=precomp $ASYNC install Zef; fi'

    - 'if [[ $BACKEND == "moar glr" ]]; then perl6 -Ilib bin/zef -v --boring $ASYNC --save-to=precomp/ build; fi'
    - 'if [[ $BACKEND == "moar glr" ]]; then perl6 -Iprecomp bin/zef -v --boring --lib=precomp $ASYNC install Zef; fi'