language: perl6
perl6:
   - 2016.07.1
   - 2016.08
   - latest
before_script:
   - rakudobrew build-panda
   - rakudobrew build zef
script:
   - zef --installed list > installed-before.txt
   - zef install .
   - zef --installed list | diff -u installed-before.txt - | sed -ne '/^[+][^+]/ { s/^[+]//; p; }' | tr "\n" "\0" | xargs -0 zef uninstall
   - rm installed-before.txt
   - panda install .
