language: perl6

perl6:
  - latest

services:
  - docker

install:
  - rakudobrew build zef
  - zef install . && spit eval 'say "hello world"'

env:
  - PATH="/home/travis/.rakudobrew/moar-nom/install/share/perl6/site/bin:$PATH"

script:
  - spit spec/base/sanity.t -d
  - spit compile resources/tools/harness.sp --RUN
