branches:
  except:
    - gh-pages
language: perl6
sudo: false
perl6:
  - latest
install:
  - rakudobrew build-panda
  - panda --notests installdeps .
  - panda-build
script:
  - PERL6LIB=lib prove -e perl6 -vr t/
