language: perl6
perl6:
  - latest
install:
  - rakudobrew build-panda
  - panda --notests installdeps .
  - panda install Test::META
script:
  - (cd t; perl6 -MTest::META -e'meta-ok')
  - prove -vr -e 'perl6 -Ilib' t/
sudo: false
