language: perl
perl:
    # -shrplib in case of a dependency on Inline::Perl5
    - '5.20-shrplib'
env:
    - BACKEND=moar
    - BACKEND=jvm
matrix:
    allow_failures:
        - env: BACKEND=jvm
sudo: false
before_install:
    # helpers $(test-jobs) and $(test-files)
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    - export PATH=~/.rakudobrew/bin:$PATH
    - rakudobrew build $BACKEND
    - perl6 -v
install:
    # must do *something* in the install phase
    - rakudobrew build-zef
    # Pull in the dependencies before running tests
   - zef --debug --depsonly install .
script:
    # tests that module passes tests *before* compile
    - prove -v -j$(test-jobs) -e "perl6 --ll-exception -Ilib" $(test-files)
after_success:
    - zef list --installed --verbose
