language: perl
perl:
    # -shrplib in case of a dependency on Inline::Perl5
    - '5.20-shrplib'
env:
    - BACKEND=moar
    - BACKEND=jvm
matrix:
    allow_failures:
        - env: BACKEND=jvm
sudo: false
before_install:
    # helpers $(test-jobs) and $(test-files)
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    - export PATH=~/.rakudobrew/bin:$PATH
    - rakudobrew build $BACKEND
    - perl6 -v
install:
    # must do *something* in the install phase
    - perl6 -e 'put "Hello World!"'
script:
    # Pull in the dependencies before running tests
    - zef install .
    # tests that module passes tests *before* compile
    - prove -v -j$(test-jobs) -e "perl6 --ll-exception -Ilib" $(test-files)
    # runs tests again, but catches some heisenbugs (mostly with precompiled modules)
after_success:
    - zef list --installed --verbose
