branches:
  only:
    - master

language: perl6

perl6:
  - latest

install:
  - rakudobrew build-zef ${TRAVIS_PERL6_VERSION#latest}
  - zef update
  - zef --depsonly install .

#cache:
#  directories:
#    - $TRAVIS_BUILD_DIR/.rakudobrew
#    - $HOME/Travis-ci
#    - $HOME/.rakudobrew
