language: perl6
perl6:
  - latest

services:
  - docker

install:
  - rakudobrew build zef

env:
  - PATH="/home/travis/.rakudobrew/moar-nom/install/share/perl6/site/bin:$PATH"

script:
  - zef install . && spit eval 'say "hello world"'
  - spit -d compile spec/base/sanity.t
  - spit prove spec/base -d=alpine,centos,debian
  - spit prove spec/packages -d=alpine,centos,debian
  - spit prove spec/docker -s -d=alpine,centos,debian
