language: perl6

perl6:
  - latest

services:
  - docker

install:
  - rakudobrew build zef
  - zef install . && spit eval 'say "hello world"'

env:
  - PATH="/home/travis/.rakudobrew/moar-nom/install/share/perl6/site/bin:$PATH"

script:
  - spit -d compile spec/base/sanity.t
  - spit compile tools/harness.spt --RUN
